# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e83d1f588066e0f26050d71b2c2e94b8"
name = "elektra-cosmetics-app"
handle = "elektra-cosmetics-app"
application_url = "https://remedy-lawn-broadway-coat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "thisisjustastorefortesting.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://remedy-lawn-broadway-coat.trycloudflare.com/auth/callback",
  "https://remedy-lawn-broadway-coat.trycloudflare.com/auth/shopify/callback",
  "https://remedy-lawn-broadway-coat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
